# Generated by Django 4.0.6 on 2022-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='summ',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
